# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 11:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_time',
            field=models.TimeField(default=datetime.datetime(2016, 1, 29, 11, 3, 34, 413347, tzinfo=utc), verbose_name='ans_time'),
            preserve_default=False,
        ),
    ]
