# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_qcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acomment_text', models.CharField(max_length=255)),
                ('acomment_time', models.DateTimeField(verbose_name='acomment_time')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Answer')),
            ],
        ),
    ]
